name: Build

on: [push, pull_request]

jobs:
  check-format-rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
          components: "rustfmt"
      - run: cargo fmt -- --check
  build-rust:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, windows, macOS]
        rust: [stable, nightly]
    steps:
      - uses: actions/checkout@v2
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
          components: "clippy"
      - run: cargo build ${{ (matrix.rust == "stable") && "--release" }}
      - run: cargo clippy
      - uses: actions/upload-artifact@v2
        if: ${{ matrix.rust === "stable" }}
        with:
          name: app-${{ matrix.os }}
          path: |
            target/release/recent-messages2
            target/release/recent-messages2.exe
  check-format-prettier:
    runs-on: ubuntu-latest
    container: node:14-stretch
    steps:
      - uses: actions/checkout@v2
      - run: cd web && npm i
      - run: ./web/node_modules/.bin/prettier --check --ignore-path ".gitignore" "**/*.md" "**/*.js" "**/*.tsx" "**/*.yml" "**/*.json"
  build-web:
    runs-on: ubuntu-latest
    container: node:${{ matrix.node }}-stretch
    strategy:
      matrix:
        node: [10, 12, 14]
    steps:
      - uses: actions/checkout@v2
      - run: cd web && npm i
      - run: cd web && npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: web
          path: web/dist/
