name: Web

on: [push, pull_request]

jobs:
  check-format:
    runs-on: ubuntu-latest
    container: node:14-stretch
    steps:
      - uses: actions/checkout@v2
      - run: cd web && npm i
      - run: ./web/node_modules/.bin/prettier --check --ignore-path ".gitignore" "**/*.md" "**/*.js" "**/*.tsx" "**/*.yml" "**/*.json"
  build:
    runs-on: ubuntu-latest
    container: node:${{ matrix.node }}-stretch
    strategy:
      matrix:
        node: [10, 12, 14]
    steps:
      - uses: actions/checkout@v2
      - run: cd web && npm i
      - run: cd web && npm run build
